name: parser_tool
version: 0.1.1
description: Parser tool is a real-time compiler and runtime engine for strongly typed PEG parsers
homepage: https://github.com/mezoni/parser_tool
environment:
  sdk: '>=2.12.0 < 3.0.0'
dependencies:
  lists: ^1.0.0
dev_dependencies:
  lints: ^1.0.0-dev.0
  test: ^1.17.3
  pedantic: ^1.11.0
